### PR TITLE
Hash browser native URLs

### PR DESCRIPTION
**Pull request by koraa**
Provides a dedicated Hash function for web browser's URL objects.

Tested on chromium/v8 and a new version of fixefox.

Necessary because:

```js
var type = (/\[object (.*)\]/i).exec(Object.prototype.toString.call(new URL("http://xkcd.com")))[1].toLowerCase();
assert(type === 'url');
```

Tests have been omitted, since this is a browser-only feature.

### CODE REVIEW

**Comment by koraa** [comment]
Wait a minute before merging please. I just found that there still is some error with this in my app. I am checking whether this is related to it.

**Comment by koraa** [comment]
OK. Found it and fixed it;

I was hashing the URL Function itself (yeah, I am working a lot with types ATM) and it didn't like it's prototype properties being accessed; thus I turned off accessing all the special properties for native functions.

Do you want me to put the fix into a separate branch or may I leave it in this one?

**Comment by addaleax** [comment]
Looks good. I’ll just use `Function.prototype.toString.call(f)` instead of `String(f)` to circumvent custom `.toString` methods.

Also – rather out of curiosity – under what circumstances did you get an error hashing the URL function? I can’t really seem to reproduce that, but I’d really be interested what the “forbidden” properties of native function protoypes are :)

**Comment by koraa** [comment]
Wait a second. I am still testing myself :)
And yep, I just added that safeguard and I mane sure that they are really functions (otherwise Function.prototype.call will throw an error itself.

And the forbidden part is `URL.prototype.*`

**Comment by koraa** [comment]
argh.

**Comment by koraa** [comment]
by the way, I need the dists for my testing, that's why I added them :)

**Comment by koraa** [comment]
I am still getting errors on my testing system...

**Comment by addaleax** [comment]
Yeah, I’m seeing that using `Function.prototype.toString.call` fails ;) I’m going to be away for a few hours, so take your time – I’ll publish 0.9.1 when you’re done. :)

**Comment by koraa** [comment]
OK. WIth the newest push, I can see no more errors, but let's wait till tomorrow evening with the patch, OK?

**Comment by addaleax** [comment]
Okay, I’ll wait till you say so; I don’t see any problems with merging cc86bcf6db2.

**Comment by koraa** [comment]
Yeah; I just wanted to check whether further probems arise; they didn't; feel free to merge it :)

**Comment by addaleax** [comment]
Merged & published as 0.9.1. :)

**Pull request merged**
