### PR TITLE
Add an option for exclude specific keys

### PR DESCRIPTION
**Pull request by tchaseker**
We need to exclude some keys from hashing process . We tried to use replacer function for this purpose but unlike JSON.stringfy replacer your function doesn't include key property.

### CODE REVIEW

**Comment by addaleax** [comment]
Hey, thank you for the pull request! If I can make a suggestion: How about turning `excludeKeys` into a function that can be provided by the user? That way, it doesn’t have to be a fixed list of keys, instead it can be as flexible as you want it to be. :)

**Comment by tchaseker** [comment]
If I understand you correctly, you suggest to convert the "excludeKeys" option into a function similar to replacer, but returns false for exclude specific key. Indeed that way is more flexible. But I think performance is also important. For example, this function is called many times in an object with hundred properties.

**Comment by addaleax** [comment]
@tchaseker Yeah, that is what I mean.

If you’re caring about performance … the current code in this PR scales linearly both in the number of excluded keys and in the number of keys on all objects – that’s not exactly ideal either … if you separate that code out into a function on its own, it should give you about the same performance (and you can even use a `Set`, which is likely to be faster for larger `excludeKeys` sets)

**Comment by addaleax** [comment]
This is available in `v1.2.0` :)

**Pull request merged**
